stations:
- frame_id: station_charger
  approach_poses: [[-0.76, 0.0, 0.0], [-0.56, 0.0, 0.0], [-0.46, 0.0, 0.0]] # in frame_id coords
  departure_poses: [[-0.8, 0.0, 0.0]]
  stop_condition:
    topic: '/power_state'
    message_field: 'charging'
    compare_value: True

- frame_id: station_travel_box
  approach_poses: [[-2.20, 0.0, 0.0], [-0.6, 0.01, -0.035], [-0.38, 0.01, -0.035], [-0.312, 0.01, -0.035]] # in frame_id coords
  departure_poses: [[-0.38, 0.01, -0.035], [-0.6, 0.01, -0.035], [-2.20, 0.0, 0.0]] # in frame_id coords