defaults:
  dcf_overlay:
    "1803sub2" : "1" # enable TPDO3 on sync
    "1A03sub0" : "1" # one entry for TPDO3
    "1A03sub1" : "0x60780010" # actual current 
  eff_from_device: "obj6078/1000.0*9.76" #CL[1]=9.76 

drive_wheel_current: &drive_wheel_current
  eff_from_device: "obj6078/1000.0*14.14" #CL[1]=14.14

nodes:
  ##Wheel 1
  fl_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-51776"# home offset
  fl_caster_r_wheel_joint:
    <<: *drive_wheel_current

  ##Wheel 2
  b_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "-173177" # home offset
  b_caster_r_wheel_joint:
    <<: *drive_wheel_current

  ##Wheel 3
  fr_caster_rotation_joint:
    dcf_overlay: # "ObjectID" : "ParameterValue" (both as strings)
      "607C": "67565" # home offset
  fr_caster_r_wheel_joint:
    <<: *drive_wheel_current
