twist_controller:
  wheels: &wheels # start front left, counter-clockwise for base_drive_chain compatibility
    - steer: fl_caster_rotation_joint
      drive: fl_caster_r_wheel_joint
      steer_neutral_position: -180.0
    - steer: bl_caster_rotation_joint
      drive: bl_caster_r_wheel_joint
      steer_neutral_position: -180.0
    - steer: br_caster_rotation_joint
      drive: br_caster_r_wheel_joint
      steer_neutral_position: 0.0
    - steer: fr_caster_rotation_joint
      drive: fr_caster_r_wheel_joint
      steer_neutral_position: 0.0


odometry_controller:
  wheels: *wheels
