nodes:
  ##Wheel 1
  fl_caster_rotation_joint:
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: -12880


  ##Wheel 2
  bl_caster_rotation_joint:
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: -12740

  ##Wheel 3
  br_caster_rotation_joint:
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: 3300

  ##Wheel 4
  fr_caster_rotation_joint:
    motor_layer:
      homing_event: 19 # -> digin
      homing_speed: -5093 # -1.0 rs/s
      homing_offset: 14000
