controller_list:
  - name: fake_arm_left_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_left_1_joint
      - arm_left_2_joint
      - arm_left_3_joint
      - arm_left_4_joint
      - arm_left_5_joint
      - arm_left_6_joint
      - arm_left_7_joint
  - name: fake_arm_right_controller
    type: $(arg fake_execution_type)
    joints:
      - arm_right_1_joint
      - arm_right_2_joint
      - arm_right_3_joint
      - arm_right_4_joint
      - arm_right_5_joint
      - arm_right_6_joint
      - arm_right_7_joint
initial:  # Define initial robot poses.
  - group: arm_left
    pose: home
  - group: arm_right
    pose: home